services:
  postgres-prod:
    image: 'postgres:15-alpine'
    container_name: smash-scoreboard-prod-db
    environment:
      POSTGRES_DB: ${POSTGRES_PROD_DB}
      POSTGRES_USER: ${POSTGRES_PROD_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PROD_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - type: volume
        source: postgres_prod_data
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_PROD_USER} -d ${POSTGRES_PROD_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smash-scoreboard-webapp
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-prod:5432/${POSTGRES_PROD_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_PROD_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PROD_PASSWORD}
    ports:
      - '127.0.0.1:8080:8080' # <== restricts access to localhost
    depends_on:
      postgres-prod:
        condition: service_healthy
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smash-scoreboard-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      postgres-prod:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_prod_data:
    name: ssbu_league_postgres_prod_data
