services:
  postgres-test:
    image: 'postgres:15-alpine'
    container_name: smash-scoreboard-test-db
    environment:
    - POSTGRES_DB=${POSTGRES_TEST_DB}
    - POSTGRES_USER=${POSTGRES_TEST_USER}
    - POSTGRES_PASSWORD=${POSTGRES_TEST_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_test_data:
