services:
  postgres-dev:
    image: 'postgres:15-alpine'
    container_name: smash-scoreboard-dev-db
    environment:
      POSTGRES_DB: ${POSTGRES_DEV_DB}
      POSTGRES_USER: ${POSTGRES_DEV_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEV_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - type: volume
        source: postgres_dev_data
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DEV_USER} -d ${POSTGRES_DEV_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smash-scoreboard-webapp-dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-dev:5432/${POSTGRES_DEV_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_DEV_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_DEV_PASSWORD}
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    depends_on:
      postgres-dev:
        condition: service_healthy
    restart: on-failure
    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smash-scoreboard-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      postgres-dev:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_dev_data:
    name: ssbu_league_postgres_dev_data
