services:
  postgres-dev:
    image: 'postgres:15-alpine'
    container_name: smash-scoreboard-dev-db
    environment:
      - 'POSTGRES_DB=smash_scoreboard'
      - 'POSTGRES_PASSWORD=dev_password'
      - 'POSTGRES_USER=dev_user'
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    # Health check removed to speed up development
    restart: unless-stopped
    
  postgres-test:
    image: 'postgres:15-alpine'
    container_name: smash-scoreboard-test-db
    environment:
      - 'POSTGRES_DB=smash_scoreboard_test'
      - 'POSTGRES_PASSWORD=test_password'
      - 'POSTGRES_USER=test_user'
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    # Health check removed to speed up development
    restart: unless-stopped

  postgres-prod:
    image: 'postgres:15-alpine'
    container_name: smash-scoreboard-prod-db
    environment:
      - 'POSTGRES_DB=smash_scoreboard_prod'
      - 'POSTGRES_PASSWORD=prod_password'
      - 'POSTGRES_USER=prod_user'
    ports:
      - '5434:5432'
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prod_user -d smash_scoreboard_prod"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smash-scoreboard-pgadmin
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@example.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    ports:
      - '5050:80'
    depends_on:
      - postgres-dev
      - postgres-test
    restart: unless-stopped

volumes:
  postgres_dev_data:
  postgres_test_data:
  postgres_prod_data:
