services:
  postgres-dev:
    image: 'postgres:15-alpine'
    container_name: smash-scoreboard-dev-db
    environment:
    - POSTGRES_DB=${POSTGRES_DEV_DB}
    - POSTGRES_USER=${POSTGRES_DEV_USER}
    - POSTGRES_PASSWORD=${POSTGRES_DEV_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smash-scoreboard-pgadmin
    environment:
    - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - postgres-dev
    restart: unless-stopped

volumes:
  postgres_dev_data:
